<?php 
session_start();
$connection = mysqli_connect('localhost', 'root', 'PeDinafaraLeopardul04!', 'users');
$secret=$_SESSION["secret"];
$email=$_SESSION["email"];
$username=$_SESSION["username"];
$userip=$_SERVER["REMOTE_ADDR"];


require_once("googleLib/GoogleAuthenticator.php");
$ga = new GoogleAuthenticator();
$qrCodeUrl=$ga->getQRCodeGoogleUrl($email,$secret,"fullvideosreplays");

$checkResult="";

if(isset($_POST["create"])){
    $errors = [];
    $errorMessage = '';

    if(!empty($_POST["code"])){
        $code=$_POST["code"];
        $checkResult=$ga->verifyCode($secret,$code,2);          //2 - 2*30 seconds=1 minute time for user to input code. 
        if($checkResult){
            $_SESSION["secret"]=$secret;
            if(isset($_SESSION["make changes"])){
                if($_SESSION["make changes"]=="username, password"){
                    $password=$_SESSION["password"];
                    if(isset($secret)){
                        $query=mysqli_query($connection,"UPDATE google_auth SET username='$username', password='$password' WHERE userip='$userip' AND secret='$secret'");
                    }else{
                        $query=mysqli_query($connection,"UPDATE google_auth SET username='$username', password='$password' WHERE userip='$userip'");
                    }
                    
                    unset($_SESSION["password"]);
                }
                if($_SESSION["make changes"]=="all"){
                    $password=$_SESSION["password"];
                    $query=mysqli_query($connection,"INSERT INTO google_auth(email,username,password,userip,secret) VALUES('$email','$username','$password','$userip','$secret')");
                    unset($_SESSION["password"]);
                }
                unset($_SESSION["make changes"]);
            }
            header("Location:index.php");
        }
        else{
            $errors[]="The code could not be verified. Please try again.";
        }
    }else{
        $errors[]="Please enter in the field the code you see on you Google Authenticator app after scanning the QR.";
    }
    
    if(!empty($errors)){
        $allErrors = join('<br/>', $errors);
        $errorMessage = "<p style='color: red;'>{$allErrors}</p>";
    }
}
?>

<html>
    <head>
        <meta charset="utf-8">
        <title>Confirm</title>
        <link rel="stylesheet" href="contact_style.css">
    </head>
    
    <body>
        <section class="header">
            <nav>
                <a href="index.php"><img src="images/logo.jpg"></a>
                <div class="nav-links" id="navLinks">
                    <i class="fa-solid fa-xmark" onclick="hideMenu()"></i>
                    <ul>
                        <li><a href="index.php" style="color: deepskyblue">Home</a></li>
                        <li><a href="porn.html" style="color: deepskyblue">Porn</a></li>
                        <li><a href="formula.php" style="color: deepskyblue">Formula</a></li>
                        <li><a href="moto.html" style="color: deepskyblue">Moto</a></li>
                        <li><a href="" style="color: deepskyblue">Top Gear</a></li>
                        <li><a href="donate.html" style="color: deepskyblue">Donate</a></li>
                        <li><a href="contact.php" style="color: deepskyblue">Contact</a></li>
                    </ul>
                </div>
                <i class="fa-solid fa-bars" onclick="showMenu()"></i>
            </nav>
            <div class="text-box">
                    <h1>Google Two Factor Authentification</h1>
                    <h2>Please enter the code generated by the Google Autentification app on your phone.</h2>
                <div class="contact-form">
                    <form id="contact-form" method="POST" action="device_confirmations.php">
                        <?php echo((!empty($errorMessage)) ? $errorMessage : '') ?>
                        <br>
                        <img src="<?php echo $qrCodeUrl; ?>"/>
                        <br>
                        <input name="code" type="text" id="code" autocomplete="off" value="" class="form-control" placeholder="Code from Google Authenticator after you scan the QR." required>
                        <br>
                        <input type="submit" class="form-control submit" value="Submit" name="create" id="create">
                    </form>
                </div>
            </div>
        </section>       
    </body>
    <script src="//cdnjs.cloudflare.com/ajax/libs/validate.js/0.13.1/validate.min.js"></script>
    <script>
      const constraints = {
          name: {
              presence: { allowEmpty: false }
          },
          email: {
              presence: { allowEmpty: false },
              email: true
          },
          message: {
              presence: { allowEmpty: false }
          }
      };

      const form = document.getElementById('contact-form');

      form.addEventListener('submit', function (event) {
          const formValues = {
              name: form.elements.name.value,
              email: form.elements.email.value,
              message: form.elements.message.value
          };

          const errors = validate(formValues, constraints);

          if (errors) {
              event.preventDefault();
              const errorMessage = Object
                  .values(errors)
                  .map(function (fieldValues) {
                      return fieldValues.join(', ')
                  })
                  .join("\n");

              alert(errorMessage);
          }
      }, false);
    </script>
    <script>
            var navLinks = document.getElementById("navLinks");
            function showMenu(){
                navLinks.style.right="0";
            }
            function hideMenu(){
                navLinks.style.right="-200px";
            }
    </script>
    <script src="js/jquery-1.12.4.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
</html>
